### ISSUE TITLE
Scope Quiz

### ISSUE THREAD

**Issue by keilkyle** [learn-co-curriculum/phase-1-quiz-scope#1]
### Canvas Link

https://learning.flatironschool.com/courses/4978/quizzes/26866

### Concern

Question is: "Lexical scope in JavaScript means that a variable defined outside a function can be accessible inside the function, but not the other way around."

And the answer you listed as correct is "true." I'd quibble with that -- didn't you just teach us that using var means that variables defined in functions are accessible globally?

### Suggested Changes

Maybe adding ", and a variable defined inside a function with const and let..." to make it more precise?

**Comment by lizbur10** [comment]
Hi @keilkyle ! Thanks for the feedback - the question has been updated to clarify 💙
